### ISSUE TITLE
No Images for the items 

### ISSUE THREAD

**Issue by LADYxPAGE** [Sagi422/sp-MexicanCafeJob#1]
Hello, I would love to use your script, but haven't been able to find images for all the items your script adds. Can you help with this?

**Comment by Sagi422** [comment]
![beef](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/6f2de0ac-8155-4bff-855b-334741707dd7)
![dirty_cup](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/6d24a748-7862-45e2-8fa8-e5d1ec916943)
![clean_cup](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/2100f9c4-257a-418b-9f35-45e45bfaa272)
![clean_food_plate](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/5a201d29-6afa-414b-9462-69159f80a51f)
![dirty_food_plate](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/71ac1e4d-1691-4bef-9775-ca67f07c081d)
![lemon](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/2395c354-e060-418d-9c81-39a49dce0413)
![sprite](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/94085e5f-8d5c-4a45-b141-86c866374d4c)
![tea_bag](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/37236a3e-447a-4f2d-9f8b-b8e4d13acdcf)
![raw_chicken](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/669ccc79-2a80-4498-a3fb-316b05b5128c)
![raw_beef](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/48db3dfd-ba3e-4580-9355-4eddb961c310)
![salsa](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/76afd9e4-5882-40ee-b693-49bc7d0bd28f)
![dough](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/5f8e8542-c099-4679-9178-dab5ad8e69bc)
![taco](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/c87e00db-3531-469d-9829-7a174bbfd311)
![chicken_burrito](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/5c1b5804-e6d7-4e93-b91b-87920fde5333)
![beef_burrito](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/4a5eb943-6d2b-427c-addb-3ed1aa30cda4)
![nachos](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/821d39f6-ed94-48a7-a4fe-185b4186d446)
![cooked_chicken](https://github.com/Sagi422/sp-MexicanCafeJob/assets/103905109/b12dec93-ef01-488d-82f5-c49f5ea8a87e)

not the best images bur here you go
